//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhomKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDat
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string GioLamViec { get; set; }
        public string GiaoHang { get; set; }
        public string HoanTien { get; set; }
        public string SDTLienHe { get; set; }
        public string EmailLienHe { get; set; }
        public string FaceBook { get; set; }
        public string GooglePlus { get; set; }
        public string Twiter { get; set; }
        public string YouTube { get; set; }
        public string Instargram { get; set; }
        public string GoogleMap { get; set; }
        public string MatKhauMail { get; set; }
    }
}
