//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhomKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int MaChiTietSanPham { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> MaNhaSanXuat { get; set; }
        public string MoTa { get; set; }
        public string ChiTiet { get; set; }
    
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
