//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhomKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTrinhNoiBat
    {
        public int MaCT { get; set; }
        public string TenCT { get; set; }
        public string AnhDaiDien { get; set; }
        public string DiaChi { get; set; }
        public string Chitiet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
