//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhomKinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int MaAnh { get; set; }
        public string TieuDe { get; set; }
        public string TieuDe1 { get; set; }
        public string TieuDe2 { get; set; }
        public string MoTa1 { get; set; }
        public string MoTa2 { get; set; }
        public string MoTa3 { get; set; }
        public string MoTa4 { get; set; }
        public string LinkAnh { get; set; }
    }
}
